name: my_gallery_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.4.1  

flutter_native_splash:
  color: "#42a5f5"
  branding: assets/icons/App_icon.png
  branding_mode: center

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/App_icon.png"


flutter:
  uses-material-design: true

  assets:
    - assets/images/
